export const siteConfig = {
  name: "Bougain Mediaa",
  tagline: "Your growth, our grind.",
  description:
    "Digital marketing agency built around storytelling, strategy, and helping businesses grow in the digital world.",
  url: process.env.NEXT_PUBLIC_SITE_URL ?? "http://localhost:3000",
};

export const contact = {
  email: "mediaabougain@gmail.com",
  phone: "+91 8138-869120",
  phoneHref: "tel:+918138869120",
  whatsapp: "+91 8138-869120",
  whatsappHref: "https://wa.me/918138869120",
  responseTime: "Usually within 2 hours",
  businessHours: "Mon – Sat, 10:00 AM – 7:00 PM IST",
  office: "Kerala, India",
  mapEmbedUrl:
    "https://www.google.com/maps?q=Kerala,+India&output=embed",
};

export const navLinks = [
  { label: "Home", href: "/" },
  { label: "Services", href: "/services" },
  { label: "Portfolio", href: "/portfolio" },
  { label: "About", href: "/about" },
  { label: "Careers", href: "/careers" },
  { label: "Contact", href: "/contact" },
] as const;

export const hero = {
  brand: "Bougain Mediaa",
  headline: ["Your", "Growth.", "Our", "Grind."],
  subheadline:
    "We blend strategy, storytelling, performance marketing, AI automation, and web experiences to help ambitious brands grow.",
  primaryCta: "Start a Conversation",
  secondaryCta: "View Our Work",
};

export const about = {
  label: "About Us",
  headline: "Marketing that means something",
  intro:
    "We're Bougain Mediaa — thinkers, creators, and problem-solvers who believe marketing should be meaningful, not just measurable.",
  extended:
    "The digital landscape shifts fast. Whether you need visibility, qualified leads, or a brand that resonates — our focus is always on results that matter.",
  consultation:
    "We'd love to learn about your business. Start with a free consultation and get a feel for who we are.",
  closing: "Looking forward to connecting.",
  mission:
    "To deliver tailored, data-driven strategies that help brands connect, engage, and thrive online.",
  vision:
    "To make marketing meaningful — where creativity meets measurable results.",
  values: [
    {
      title: "Story first",
      description: "Every campaign begins with a narrative people care about.",
    },
    {
      title: "Clarity over noise",
      description: "Fewer moves, sharper decisions, measurable progress.",
    },
    {
      title: "Human craft",
      description: "Strategy shaped by people, refined by data — never the reverse.",
    },
  ],
  timeline: [
    {
      year: "01",
      title: "Listen deeply",
      description: "We learn your brand, audience, and the real business problem.",
    },
    {
      year: "02",
      title: "Shape the narrative",
      description: "Positioning, messaging, and creative direction built to last.",
    },
    {
      year: "03",
      title: "Activate channels",
      description: "Paid, organic, and owned media working as one system.",
    },
    {
      year: "04",
      title: "Measure & refine",
      description: "Transparent reporting and continuous optimization.",
    },
  ],
  cards: [
    {
      title: "Our Story",
      content:
        "A digital marketing agency built around storytelling, strategy, and real business growth.",
    },
    {
      title: "Mission",
      content:
        "To deliver tailored, data-driven strategies that help brands connect, engage, and thrive online.",
    },
    {
      title: "Vision",
      content:
        "To make marketing meaningful — where creativity meets measurable results.",
    },
  ],
};

export const services = {
  label: "What We Do",
  headline: "Services",
  subtitle:
    "Helping ambitious brands grow through strategy, creativity & digital experiences.",
  items: [
    {
      title: "Content Creation",
      description:
        "Creative concepts and branded content designed to tell your story clearly.",
      tag: "Creative",
      image: "/images/sevices/content creation.png",
      features: [
        "Content strategy and ideation",
        "Brand-first copy and captions",
        "Platform-ready creative assets",
      ],
      stats: [
        { value: "1.2K+", label: "Assets Created" },
        { value: "40+", label: "Brand Systems" },
        { value: "98%", label: "Client Retention" },
      ],
    },
    {
      title: "Video Production",
      description:
        "End-to-end video production for campaigns, social content, and branded storytelling.",
      tag: "Video",
      image: "/images/sevices/video production.png",
      features: [
        "Creative direction and scripting",
        "Shoot planning and production",
        "Editing, motion, and delivery",
      ],
      stats: [
        { value: "300+", label: "Videos Produced" },
        { value: "50+", label: "Campaign Films" },
        { value: "95%", label: "On-Time Delivery" },
      ],
    },
    {
      title: "Visual Ads",
      description:
        "High-impact ad creatives crafted to stop the scroll and drive action.",
      tag: "Design",
      image: "/images/sevices/visualadss.png",
      features: [
        "Static and motion ad creatives",
        "Multi-format ad variants",
        "Creative testing support",
      ],
      stats: [
        { value: "900+", label: "Ad Creatives" },
        { value: "120+", label: "Campaign Sets" },
        { value: "3.9×", label: "CTR Lift" },
      ],
    },
    {
      title: "Social Media Management",
      description:
        "Consistent social presence through strategy, posting, and audience engagement.",
      tag: "Social",
      image: "/images/sevices/social media management.png",
      features: [
        "Monthly social media planning",
        "Content calendar and publishing",
        "Community management",
      ],
      stats: [
        { value: "180+", label: "Accounts Managed" },
        { value: "2M+", label: "Audience Reach" },
        { value: "4.8×", label: "Engagement Lift" },
      ],
    },
    {
      title: "Brand Shoots",
      description:
        "Professional photo and video shoots that elevate your brand identity.",
      tag: "Branding",
      image: "/images/sevices/brand shoots.png",
      features: [
        "Concept and moodboard planning",
        "On-location or studio shoots",
        "Brand-ready media selection",
      ],
      stats: [
        { value: "120+", label: "Brand Shoots" },
        { value: "2.5K+", label: "Final Visuals" },
        { value: "96%", label: "Client Satisfaction" },
      ],
    },
    {
      title: "Performance Marketing",
      description:
        "Data-driven paid and retention campaigns focused on conversions and measurable growth.",
      tag: "Paid Growth",
      image: "/images/sevices/perfomance marketing.png",
      features: [
        "Meta Ads",
        "Google Ads",
        "WhatsApp Campaigns",
        "Email Marketing",
      ],
      stats: [
        { value: "250+", label: "Campaigns" },
        { value: "500M+", label: "Reach" },
        { value: "3.2×", label: "Avg. ROAS" },
      ],
    },
  ],
  approach: [
    {
      step: "01",
      title: "Discover",
      description: "We learn your goals, audience, and competitive landscape.",
    },
    {
      step: "02",
      title: "Strategize",
      description: "A tailored plan built around measurable outcomes.",
    },
    {
      step: "03",
      title: "Deliver",
      description: "Execute, optimize, and report — so you see real growth.",
    },
  ],
};

export const stats = [
  { value: 50, suffix: "+", label: "Projects Delivered" },
  { value: 30, suffix: "+", label: "Happy Clients" },
  { value: 1, suffix: "M+", label: "Social Reach" },
  { value: 100, suffix: "+", label: "Campaigns Run" },
];

export type PortfolioSection = "content-videos" | "ai-concept-ads" | "video-production";

export const portfolioCategories = [
  "All",
  "Hospitality & Events",
  "Real Estate & Interiors",
  "Fitness & Lifestyle",
  "EdTech & Tech",
  "Food & Brand Shoots",
] as const;

export type PortfolioCategory = (typeof portfolioCategories)[number];

export interface PortfolioItem {
  id: string;
  title: string;
  client: string;
  category: PortfolioCategory;
  type: "video" | "photo";
  industry: string;
  result: string;
  description: string;
  image: string;
  videoSrc?: string;
  aspect?: "16:9" | "9:16" | "4:3";
  span: "lg" | "sm" | "md";
  featured?: boolean;
  section?: PortfolioSection;
}

export const portfolio: {
  label: string;
  headline: string;
  subtitle: string;
  items: PortfolioItem[];
} = {
  label: "Work We're Proud Of",
  headline: "Selected Work in Motion",
  subtitle: "Content videos, AI concept ads, and commercial video production.",
  items: [
    // ── Section 1: Content Videos (24 Clean Web-Safe WebM Videos) ──
    {
      id: "cv-turnup-crown-plaza",
      title: "Crown Plaza Turn Up Aftermovie",
      client: "Crowne Plaza Hotels",
      category: "Hospitality & Events",
      type: "video",
      industry: "Luxury Hospitality",
      result: "1.8M+ video impressions",
      description: "High-energy event aftermovie and visual storytelling for Crowne Plaza.",
      image: "",
      videoSrc: "/videos/content/turn-up-crown-plaza.webm",
      aspect: "16:9",
      span: "lg",
      featured: true,
      section: "content-videos",
    },
    {
      id: "cv-boss-reel",
      title: "Boss Brand Commercial",
      client: "Boss Wear & Lifestyle",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Apparel & Lifestyle",
      result: "420K+ campaign reach",
      description: "Commercial film blending street culture aesthetics with sleek fashion.",
      image: "",
      videoSrc: "/videos/content/boss-reel-final.webm",
      aspect: "16:9",
      span: "lg",
      featured: true,
      section: "content-videos",
    },
    {
      id: "cv-chefs-kiss",
      title: "Chef's Kiss Culinary Story",
      client: "Chef's Kiss Dining",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Culinary & Dining",
      result: "250K+ organic views",
      description: "Sensory food cinematography capturing artisanal prep and plating perfection.",
      image: "",
      videoSrc: "/videos/content/chefs-kiss-final-out.webm",
      aspect: "9:16",
      span: "sm",
      featured: true,
      section: "content-videos",
    },
    {
      id: "cv-first-draft-emarath",
      title: "Emarath Architecture Showcase",
      client: "Emarath Interiors",
      category: "Real Estate & Interiors",
      type: "video",
      industry: "Interior Architecture",
      result: "3.4× qualified leads",
      description: "Cinematic interior walkthrough showcasing Scandinavian aesthetics.",
      image: "",
      videoSrc: "/videos/content/first-draft-emarath.webm",
      aspect: "16:9",
      span: "lg",
      featured: true,
      section: "content-videos",
    },
    {
      id: "cv-got-emarath",
      title: "GOT Emarath Interior Film",
      client: "Emarath Interiors",
      category: "Real Estate & Interiors",
      type: "video",
      industry: "Architecture",
      result: "Featured design award",
      description: "Interior design documentary capturing space planning and lighting.",
      image: "",
      videoSrc: "/videos/content/got-emarath-1.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-fit-co-reel-1",
      title: "Fit & Co Brand Launch Reel",
      client: "Fit & Co Gyms",
      category: "Fitness & Lifestyle",
      type: "video",
      industry: "Fitness & Health",
      result: "4.8× engagement lift",
      description: "Fast-paced mobile reel engineered for scroll-stopping engagement.",
      image: "",
      videoSrc: "/videos/content/fit-co-reel-1.webm",
      aspect: "9:16",
      span: "sm",
      featured: true,
      section: "content-videos",
    },
    {
      id: "cv-godha-reel",
      title: "Godha Fitness Action Film",
      client: "Godha Fitness",
      category: "Fitness & Lifestyle",
      type: "video",
      industry: "Sports & Athletics",
      result: "5.2× reach lift",
      description: "Raw cinematic edit focusing on athletic strength and endurance.",
      image: "",
      videoSrc: "/videos/content/godha-reel-final.webm",
      aspect: "9:16",
      span: "sm",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-happy-2",
      title: "Happy Brand Event Film",
      client: "Happy Media",
      category: "Hospitality & Events",
      type: "video",
      industry: "Entertainment",
      result: "500K+ cross-platform views",
      description: "Vibrant event campaign film showcasing celebratory crowd energy.",
      image: "",
      videoSrc: "/videos/content/happy-2.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-aicademy-new-reel",
      title: "Aicademy Future Learning Reel",
      client: "Aicademy Global",
      category: "EdTech & Tech",
      type: "video",
      industry: "EdTech",
      result: "2.1× signup lift",
      description: "Modern promotional reel highlighting AI-powered education.",
      image: "",
      videoSrc: "/videos/content/aicademy-new-reel.webm",
      aspect: "9:16",
      span: "sm",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-getwork-vid",
      title: "GetWork Platform Launch Video",
      client: "GetWork App",
      category: "EdTech & Tech",
      type: "video",
      industry: "SaaS & Tech",
      result: "180K+ app impressions",
      description: "Sleek motion graphics and video ad showcasing user workflow.",
      image: "",
      videoSrc: "/videos/content/getwork-vid-fdraft-2.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-emarath-interior-finalll",
      title: "Emarath Interior Draft Preview",
      client: "Emarath Interiors",
      category: "Real Estate & Interiors",
      type: "video",
      industry: "Interior Design",
      result: "High client conversion",
      description: "Preview edit of luxury residential interior project.",
      image: "",
      videoSrc: "/videos/content/emarath-interior-draft-preview.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-gwnad",
      title: "GWN Commercial Reel",
      client: "GWN Brand",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Brand Shoots",
      result: "Brand engagement lift",
      description: "High-impact brand shoot commercial.",
      image: "",
      videoSrc: "/videos/content/gwnad.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-keyboard-reel",
      title: "Tech Keyboard Product Reel",
      client: "Tech Brand Lab",
      category: "EdTech & Tech",
      type: "video",
      industry: "Consumer Electronics",
      result: "3.9× CTR lift",
      description: "Close-up macro product video emphasizing tactile switches and RGB lighting.",
      image: "",
      videoSrc: "/videos/content/keyboard-reel-final-draftt.webm",
      aspect: "9:16",
      span: "sm",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-r2v2",
      title: "R2V2 Brand Film",
      client: "R2 Media",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Commercial",
      result: "High organic views",
      description: "Dynamic commercial video edit.",
      image: "",
      videoSrc: "/videos/content/r2v2.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-reel-2-fitgo",
      title: "FitGo High-Intensity Reel",
      client: "FitGo Gyms",
      category: "Fitness & Lifestyle",
      type: "video",
      industry: "Fitness",
      result: "320K+ views",
      description: "Dynamic workout reel highlighting trainer sessions.",
      image: "",
      videoSrc: "/videos/content/reel-2-fitgo.webm",
      aspect: "9:16",
      span: "sm",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-revathy-reel",
      title: "Revathy Lifestyle Reel",
      client: "Revathy Media",
      category: "Fitness & Lifestyle",
      type: "video",
      industry: "Personal Brand",
      result: "92K+ organic impressions",
      description: "Minimalist fashion aesthetic reel focused on personal branding.",
      image: "",
      videoSrc: "/videos/content/revathy-reel-1draft.webm",
      aspect: "9:16",
      span: "sm",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v-3",
      title: "V3 Commercial Edit",
      client: "Bougain Mediaa",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Brand Film",
      result: "Client approved",
      description: "Creative commercial brand video.",
      image: "",
      videoSrc: "/videos/content/v-3.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v-4",
      title: "V4 Creative Spot",
      client: "Bougain Mediaa",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Brand Film",
      result: "High engagement",
      description: "Creative promotional video spot.",
      image: "",
      videoSrc: "/videos/content/v-4.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v4-mov",
      title: "V4 Motion Cut",
      client: "Bougain Mediaa",
      category: "Hospitality & Events",
      type: "video",
      industry: "Motion Graphics",
      result: "Featured video",
      description: "Sleek motion edit for commercial client.",
      image: "",
      videoSrc: "/videos/content/v4-cut.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v2",
      title: "V2 Brand Narrative",
      client: "Bougain Mediaa",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Brand Film",
      result: "High CTR",
      description: "Narrative commercial video shoot.",
      image: "",
      videoSrc: "/videos/content/v2.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v3-raw-a",
      title: "V3 Raw Cinematic Cut",
      client: "Bougain Mediaa",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Cinematography",
      result: "High quality edit",
      description: "Cinematic cut showcasing rich visual color grading.",
      image: "",
      videoSrc: "/videos/content/v3-raw-a.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v6",
      title: "V6 Commercial Reel",
      client: "Bougain Mediaa",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Brand Shoots",
      result: "Top performance",
      description: "Commercial edit designed for digital campaign launch.",
      image: "",
      videoSrc: "/videos/content/v6.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-v7-a",
      title: "V7 Extended Commercial",
      client: "Bougain Mediaa",
      category: "Hospitality & Events",
      type: "video",
      industry: "Campaign Film",
      result: "1M+ impressions",
      description: "Full length campaign commercial film.",
      image: "",
      videoSrc: "/videos/content/v7-a.webm",
      aspect: "16:9",
      span: "lg",
      featured: false,
      section: "content-videos",
    },
    {
      id: "cv-vc-1",
      title: "VC1 Visual Creative",
      client: "Bougain Mediaa",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "Visual Ads",
      result: "3.5× ROAS",
      description: "High impact ad creative for social platforms.",
      image: "",
      videoSrc: "/videos/content/vc-1.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "content-videos",
    },

    // ── Section 2: AI Concept Ads (15 WebM AI Videos) ──
    {
      id: "ai-amruth-concept",
      title: "Amruth Concept Ad",
      client: "Amruth",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/AMRUTH CONCEPT AD.webm",
      aspect: "16:9",
      span: "lg",
      featured: true,
      section: "ai-concept-ads",
    },
    {
      id: "ai-easter-video",
      title: "Easter Video Concept",
      client: "Brand Client",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/EASTER VIDEO.webm",
      aspect: "16:9",
      span: "lg",
      featured: true,
      section: "ai-concept-ads",
    },
    {
      id: "ai-hayyak-ad",
      title: "Hayyak Commercial",
      client: "Hayyak",
      category: "Hospitality & Events",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/HAYYAK AD VIDEO.webm",
      aspect: "16:9",
      span: "md",
      featured: true,
      section: "ai-concept-ads",
    },
    {
      id: "ai-hna-gst",
      title: "HNA GST Advisory Ad",
      client: "HNA",
      category: "EdTech & Tech",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/HNA AD GST.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-kitkat-ad",
      title: "KitKat Concept Ad",
      client: "KitKat",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/kitkat ad stibe final.webm",
      aspect: "16:9",
      span: "lg",
      featured: true,
      section: "ai-concept-ads",
    },
    {
      id: "ai-mango-bite",
      title: "Mango Bite Ad",
      client: "Mango Bite",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/mango bite ad.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-milma-ad",
      title: "Milma Dairy Commercial",
      client: "Milma",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/milma ad.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-raihat-al-zuhar",
      title: "Raihat Al Zuhar Luxury Fragrance",
      client: "Raihat",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/RAIHAT AL ZUHAR.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-raihat-udiyya",
      title: "Raihat Udiyya Perfume",
      client: "Raihat",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/RAIHAT UDIYYA.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-solar-extrawatt",
      title: "Extrawatt Solar Energy Ad",
      client: "Extrawatt",
      category: "EdTech & Tech",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/solar ad extrawatt.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-toms-pipes-concept",
      title: "Toms Pipes Concept Ad",
      client: "Toms Pipes",
      category: "EdTech & Tech",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/TOMS PIPES CONCEPT AD.webm",
      aspect: "16:9",
      span: "md",
      featured: true,
      section: "ai-concept-ads",
    },
    {
      id: "ai-toms-meteor",
      title: "Toms Pipes Meteor Ad",
      client: "Toms Pipes",
      category: "EdTech & Tech",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/TOMS PIPES METEOR AD.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-toms-pipes",
      title: "Toms Pipes Commercial",
      client: "Toms Pipes",
      category: "EdTech & Tech",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/toms pipes.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-uddiya-raihat-zuhar",
      title: "Uddiya Raihat Al Zuhar Ad",
      client: "Raihat",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/UDDIYA RAIHAT AL ZUHAR.webm",
      aspect: "16:9",
      span: "md",
      featured: false,
      section: "ai-concept-ads",
    },
    {
      id: "ai-udiyya-ad-raihat",
      title: "Udiyya Raihat Fragrance Ad",
      client: "Raihat",
      category: "Food & Brand Shoots",
      type: "video",
      industry: "AI Concept",
      result: "",
      description: "",
      image: "",
      videoSrc: "/videos/AI/UDIYYA ad raihat.webm",
      aspect: "16:9",
      span: "sm",
      featured: false,
      section: "ai-concept-ads",
    },
  ],
};

export const images = {
  hero: "/images/hero-bg.png",
  about: "/images/about-team.png",
  careers: "/images/careers-team.png",
  cta: "/images/cta-bg.png",
};

export const logos = {
  fullGreen: "/logos/logo-full-green.png",
  fullWhite: "/logos/logo-full-white.png",
  iconGreen: "/logos/BM%20LOGO%20icon%20G-01.png",
  iconWhite: "/logos/BM%20LOGO%20Icon%20W-01-01.png",
};

export const ctaBand = {
  headline: "Ready to grow?",
  subheadline: "Get a free consultation and let's build something great together.",
};

export const contactSection = {
  headline: "Let's make something exceptional",
  supporting:
    "Tell us about your brand. We'll respond personally — usually within a few hours.",
};

export const careers = {
  headline: "Join Our Team",
  subheadline:
    "We're thinkers, creators, and problem-solvers. If you're passionate about digital marketing and want to do meaningful work, we'd love to hear from you.",
  emptyState:
    "We don't have any open positions right now — but we're always interested in meeting talented people. Send your resume to mediaabougain@gmail.com and we'll keep you in mind.",
  whyJoin: [
    {
      title: "Creative Work",
      description: "Work on diverse brands and campaigns that make a real impact.",
    },
    {
      title: "Growth Culture",
      description: "Learn fast, experiment boldly, and level up your skills.",
    },
    {
      title: "Meaningful Impact",
      description: "Marketing that matters — not just vanity metrics.",
    },
  ],
  filters: ["All", "Full-time", "Remote", "Part-time", "Internship"],
  ctaBand: {
    headline: "Don't see a fit?",
    subheadline:
      "Send us your resume — we're always interested in meeting talented people.",
  },
};

export const footer = {
  quickLinks: navLinks,
  supportLinks: [
    { label: "Privacy Policy", href: "#" },
    { label: "Get a Quote", href: "/contact" },
  ],
  copyright: `© ${new Date().getFullYear()} Bougain Mediaa. All rights reserved.`,
};
