-- Seed Initial Services and Portfolio Items into PostgreSQL

INSERT INTO services (id, title, description, tag, image, features, stats, order_index) VALUES
('content-creation', 'Content Creation', 'Creative concepts and branded content designed to tell your story clearly.', 'Creative', '/images/sevices/content creation.png', '["Content strategy and ideation", "Brand-first copy and captions", "Platform-ready creative assets"]'::jsonb, '[{"value": "1.2K+", "label": "Assets Created"}, {"value": "40+", "label": "Brand Systems"}, {"value": "98%", "label": "Client Retention"}]'::jsonb, 1),
('video-production', 'Video Production', 'End-to-end video production for campaigns, social content, and branded storytelling.', 'Video', '/images/sevices/video production.png', '["Creative direction and scripting", "Shoot planning and production", "Editing, motion, and delivery"]'::jsonb, '[{"value": "300+", "label": "Videos Produced"}, {"value": "50+", "label": "Campaign Films"}, {"value": "95%", "label": "On-Time Delivery"}]'::jsonb, 2),
('visual-ads', 'Visual Ads', 'High-impact ad creatives crafted to stop the scroll and drive action.', 'Design', '/images/sevices/visualadss.png', '["Static and motion ad creatives", "Multi-format ad variants", "Creative testing support"]'::jsonb, '[{"value": "900+", "label": "Ad Creatives"}, {"value": "120+", "label": "Campaign Sets"}, {"value": "3.9×", "label": "CTR Lift"}]'::jsonb, 3),
('social-media-management', 'Social Media Management', 'Consistent social presence through strategy, posting, and audience engagement.', 'Social', '/images/sevices/social media management.png', '["Monthly social media planning", "Content calendar and publishing", "Community management"]'::jsonb, '[{"value": "180+", "label": "Accounts Managed"}, {"value": "2M+", "label": "Audience Reach"}, {"value": "4.8×", "label": "Engagement Lift"}]'::jsonb, 4),
('brand-shoots', 'Brand Shoots', 'Professional photo and video shoots that elevate your brand identity.', 'Branding', '/images/sevices/brand shoots.png', '["Concept and moodboard planning", "On-location or studio shoots", "Brand-ready media selection"]'::jsonb, '[{"value": "120+", "label": "Brand Shoots"}, {"value": "2.5K+", "label": "Final Visuals"}, {"value": "96%", "label": "Client Satisfaction"}]'::jsonb, 5),
('performance-marketing', 'Performance Marketing', 'Data-driven paid and retention campaigns focused on conversions and measurable growth.', 'Paid Growth', '/images/sevices/perfomance marketing.png', '["Meta Ads", "Google Ads", "WhatsApp Campaigns", "Email Marketing"]'::jsonb, '[{"value": "250+", "label": "Campaigns"}, {"value": "500M+", "label": "Reach"}, {"value": "3.2×", "label": "Avg. ROAS"}]'::jsonb, 6)
ON CONFLICT (id) DO NOTHING;

DELETE FROM portfolio_items;

INSERT INTO portfolio_items (id, title, client, category, type, industry, result, description, image, video_src, aspect, span, featured, section, order_index) VALUES
('cv-turnup-crown-plaza', 'Crown Plaza Turn Up Aftermovie', 'Crowne Plaza Hotels', 'Hospitality & Events', 'video', 'Luxury Hospitality', '1.8M+ video impressions', 'High-energy event aftermovie and visual storytelling for Crowne Plaza.', '', '/videos/AI/TURN UP CROWN PLAZA.webm', '16:9', 'lg', true, 'content-videos', 1),
('cv-boss-reel', 'Boss Brand Commercial', 'Boss Wear & Lifestyle', 'Food & Brand Shoots', 'video', 'Apparel & Lifestyle', '420K+ campaign reach', 'Commercial film blending street culture aesthetics with sleek fashion.', '', '/videos/AI/BOSS REEL_FINAL.webm', '16:9', 'lg', true, 'content-videos', 2),
('cv-chefs-kiss', 'Chef''s Kiss Culinary Story', 'Chef''s Kiss Dining', 'Food & Brand Shoots', 'video', 'Culinary & Dining', '250K+ organic views', 'Sensory food cinematography capturing artisanal prep and plating perfection.', '', '/videos/AI/chefs kiss_FINAL OUT.webm', '9:16', 'sm', true, 'content-videos', 3),
('cv-first-draft-emarath', 'Emarath Architecture Showcase', 'Emarath Interiors', 'Real Estate & Interiors', 'video', 'Interior Architecture', '3.4× qualified leads', 'Cinematic interior walkthrough showcasing Scandinavian aesthetics.', '', '/videos/AI/first draft emarath.webm', '16:9', 'lg', true, 'content-videos', 4),
('cv-got-emarath', 'GOT Emarath Interior Film', 'Emarath Interiors', 'Real Estate & Interiors', 'video', 'Architecture', 'Featured design award', 'Interior design documentary capturing space planning and lighting.', '', '/videos/AI/GOT emarath_1.webm', '16:9', 'md', false, 'content-videos', 5),
('cv-fit-co-reel-1', 'Fit & Co Brand Launch Reel', 'Fit & Co Gyms', 'Fitness & Lifestyle', 'video', 'Fitness & Health', '4.8× engagement lift', 'Fast-paced mobile reel engineered for scroll-stopping engagement.', '', '/videos/AI/Fit&Co Reel 1.webm', '9:16', 'sm', true, 'content-videos', 6),
('cv-godha-reel', 'Godha Fitness Action Film', 'Godha Fitness', 'Fitness & Lifestyle', 'video', 'Sports & Athletics', '5.2× reach lift', 'Raw cinematic edit focusing on athletic strength and endurance.', '', '/videos/AI/godha reel final.webm', '9:16', 'sm', false, 'content-videos', 7),
('cv-happy-2', 'Happy Brand Event Film', 'Happy Media', 'Hospitality & Events', 'video', 'Entertainment', '500K+ cross-platform views', 'Vibrant event campaign film showcasing celebratory crowd energy.', '', '/videos/AI/HAPPY_2.webm', '16:9', 'md', false, 'content-videos', 8),
('cv-aicademy-new-reel', 'Aicademy Future Learning Reel', 'Aicademy Global', 'EdTech & Tech', 'video', 'EdTech', '2.1× signup lift', 'Modern promotional reel highlighting AI-powered education.', '', '/videos/AI/Aicademy New Reel.webm', '9:16', 'sm', false, 'content-videos', 9),
('cv-getwork-vid', 'GetWork Platform Launch Video', 'GetWork App', 'EdTech & Tech', 'video', 'SaaS & Tech', '180K+ app impressions', 'Sleek motion graphics and video ad showcasing user workflow.', '', '/videos/AI/Getwork Vid Fdraft 2.webm', '16:9', 'md', false, 'content-videos', 10),
('cv-emarath-interior-finalll', 'Emarath Interior Draft Preview', 'Emarath Interiors', 'Real Estate & Interiors', 'video', 'Interior Design', 'High client conversion', 'Preview edit of luxury residential interior project.', '', '/videos/AI/Emarath Interior Finalll Draft_preview.webm', '16:9', 'md', false, 'content-videos', 11),
('cv-gwnad', 'GWN Commercial Reel', 'GWN Brand', 'Food & Brand Shoots', 'video', 'Brand Shoots', 'Brand engagement lift', 'High-impact brand shoot commercial.', '', '/videos/AI/Gwnad.webm', '16:9', 'sm', false, 'content-videos', 12),
('cv-keyboard-reel', 'Tech Keyboard Product Reel', 'Tech Brand Lab', 'EdTech & Tech', 'video', 'Consumer Electronics', '3.9× CTR lift', 'Close-up macro product video emphasizing tactile switches and RGB lighting.', '', '/videos/AI/keyboard reel final draftt.webm', '9:16', 'sm', false, 'content-videos', 13),
('cv-r2v2', 'R2V2 Brand Film', 'R2 Media', 'Food & Brand Shoots', 'video', 'Commercial', 'High organic views', 'Dynamic commercial video edit.', '', '/videos/AI/R2V2.webm', '16:9', 'md', false, 'content-videos', 14),
('cv-reel-2-fitgo', 'FitGo High-Intensity Reel', 'FitGo Gyms', 'Fitness & Lifestyle', 'video', 'Fitness', '320K+ views', 'Dynamic workout reel highlighting trainer sessions.', '', '/videos/AI/REEL 2 FitGo.webm', '9:16', 'sm', false, 'content-videos', 15),
('cv-revathy-reel', 'Revathy Lifestyle Reel', 'Revathy Media', 'Fitness & Lifestyle', 'video', 'Personal Brand', '92K+ organic impressions', 'Minimalist fashion aesthetic reel focused on personal branding.', '', '/videos/AI/Revathy Reel 1Draft.webm', '9:16', 'sm', false, 'content-videos', 16),
('cv-v-3', 'V3 Commercial Edit', 'Bougain Mediaa', 'Food & Brand Shoots', 'video', 'Brand Film', 'Client approved', 'Creative commercial brand video.', '', '/videos/AI/V 3.webm', '16:9', 'md', false, 'content-videos', 17),
('cv-v-4', 'V4 Creative Spot', 'Bougain Mediaa', 'Food & Brand Shoots', 'video', 'Brand Film', 'High engagement', 'Creative promotional video spot.', '', '/videos/AI/V 4.webm', '16:9', 'md', false, 'content-videos', 18),
('cv-v4-mov', 'V4 Motion Cut', 'Bougain Mediaa', 'Hospitality & Events', 'video', 'Motion Graphics', 'Featured video', 'Sleek motion edit for commercial client.', '', '/videos/AI/V4.webm', '16:9', 'md', false, 'content-videos', 19),
('cv-v2', 'V2 Brand Narrative', 'Bougain Mediaa', 'Food & Brand Shoots', 'video', 'Brand Film', 'High CTR', 'Narrative commercial video shoot.', '', '/videos/AI/v2.webm', '16:9', 'md', false, 'content-videos', 20),
('cv-v3-raw-a', 'V3 Raw Cinematic Cut', 'Bougain Mediaa', 'Food & Brand Shoots', 'video', 'Cinematography', 'High quality edit', 'Cinematic cut showcasing rich visual color grading.', '', '/videos/AI/v3 raw A.webm', '16:9', 'md', false, 'content-videos', 21),
('cv-v6', 'V6 Commercial Reel', 'Bougain Mediaa', 'Food & Brand Shoots', 'video', 'Brand Shoots', 'Top performance', 'Commercial edit designed for digital campaign launch.', '', '/videos/AI/v6.webm', '16:9', 'md', false, 'content-videos', 22),
('cv-v7-a', 'V7 Extended Commercial', 'Bougain Mediaa', 'Hospitality & Events', 'video', 'Campaign Film', '1M+ impressions', 'Full length campaign commercial film.', '', '/videos/AI/v7 a.webm', '16:9', 'lg', false, 'content-videos', 23),
('cv-vc-1', 'VC1 Visual Creative', 'Bougain Mediaa', 'Food & Brand Shoots', 'video', 'Visual Ads', '3.5× ROAS', 'High impact ad creative for social platforms.', '', '/videos/AI/vc 1.webm', '16:9', 'md', false, 'content-videos', 24),
('ai-amruth-concept', 'Amruth Concept Ad', 'Amruth', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/AMRUTH CONCEPT AD.webm', '16:9', 'lg', true, 'ai-concept-ads', 25),
('ai-easter-video', 'Easter Video Concept', 'Brand Client', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/EASTER VIDEO.webm', '16:9', 'lg', true, 'ai-concept-ads', 26),
('ai-hayyak-ad', 'Hayyak Commercial', 'Hayyak', 'Hospitality & Events', 'video', 'AI Concept', '', '', '', '/videos/AI/HAYYAK AD VIDEO.webm', '16:9', 'md', true, 'ai-concept-ads', 27),
('ai-hna-gst', 'HNA GST Advisory Ad', 'HNA', 'EdTech & Tech', 'video', 'AI Concept', '', '', '', '/videos/AI/HNA AD GST.webm', '16:9', 'sm', false, 'ai-concept-ads', 28),
('ai-kitkat-ad', 'KitKat Concept Ad', 'KitKat', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/kitkat ad stibe final.webm', '16:9', 'lg', true, 'ai-concept-ads', 29),
('ai-mango-bite', 'Mango Bite Ad', 'Mango Bite', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/mango bite ad.webm', '16:9', 'md', false, 'ai-concept-ads', 30),
('ai-milma-ad', 'Milma Dairy Commercial', 'Milma', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/milma ad.webm', '16:9', 'sm', false, 'ai-concept-ads', 31),
('ai-raihat-al-zuhar', 'Raihat Al Zuhar Luxury Fragrance', 'Raihat', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/RAIHAT AL ZUHAR.webm', '16:9', 'sm', false, 'ai-concept-ads', 32),
('ai-raihat-udiyya', 'Raihat Udiyya Perfume', 'Raihat', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/RAIHAT UDIYYA.webm', '16:9', 'sm', false, 'ai-concept-ads', 33),
('ai-solar-extrawatt', 'Extrawatt Solar Energy Ad', 'Extrawatt', 'EdTech & Tech', 'video', 'AI Concept', '', '', '', '/videos/AI/solar ad extrawatt.webm', '16:9', 'sm', false, 'ai-concept-ads', 34),
('ai-toms-pipes-concept', 'Toms Pipes Concept Ad', 'Toms Pipes', 'EdTech & Tech', 'video', 'AI Concept', '', '', '', '/videos/AI/TOMS PIPES CONCEPT AD.webm', '16:9', 'md', true, 'ai-concept-ads', 35),
('ai-toms-meteor', 'Toms Pipes Meteor Ad', 'Toms Pipes', 'EdTech & Tech', 'video', 'AI Concept', '', '', '', '/videos/AI/TOMS PIPES METEOR AD.webm', '16:9', 'sm', false, 'ai-concept-ads', 36),
('ai-toms-pipes', 'Toms Pipes Commercial', 'Toms Pipes', 'EdTech & Tech', 'video', 'AI Concept', '', '', '', '/videos/AI/toms pipes.webm', '16:9', 'md', false, 'ai-concept-ads', 37),
('ai-uddiya-raihat-zuhar', 'Uddiya Raihat Al Zuhar Ad', 'Raihat', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/UDDIYA RAIHAT AL ZUHAR.webm', '16:9', 'md', false, 'ai-concept-ads', 38),
('ai-udiyya-ad-raihat', 'Udiyya Raihat Fragrance Ad', 'Raihat', 'Food & Brand Shoots', 'video', 'AI Concept', '', '', '', '/videos/AI/UDIYYA ad raihat.webm', '16:9', 'sm', false, 'ai-concept-ads', 39);
