-- Seed Initial Services and Portfolio Items into PostgreSQL

INSERT INTO services (id, title, description, tag, image, features, stats, order_index) VALUES
('content-creation', 'Content Creation', 'Creative concepts and branded content designed to tell your story clearly.', 'Creative', '/images/sevices/content creation.png', '["Content strategy and ideation", "Brand-first copy and captions", "Platform-ready creative assets"]'::jsonb, '[{"value": "1.2K+", "label": "Assets Created"}, {"value": "40+", "label": "Brand Systems"}, {"value": "98%", "label": "Client Retention"}]'::jsonb, 1),
('video-production', 'Video Production', 'End-to-end video production for campaigns, social content, and branded storytelling.', 'Video', '/images/sevices/video production.png', '["Creative direction and scripting", "Shoot planning and production", "Editing, motion, and delivery"]'::jsonb, '[{"value": "300+", "label": "Videos Produced"}, {"value": "50+", "label": "Campaign Films"}, {"value": "95%", "label": "On-Time Delivery"}]'::jsonb, 2),
('visual-ads', 'Visual Ads', 'High-impact ad creatives crafted to stop the scroll and drive action.', 'Design', '/images/sevices/visualadss.png', '["Static and motion ad creatives", "Multi-format ad variants", "Creative testing support"]'::jsonb, '[{"value": "900+", "label": "Ad Creatives"}, {"value": "120+", "label": "Campaign Sets"}, {"value": "3.9×", "label": "CTR Lift"}]'::jsonb, 3),
('social-media-management', 'Social Media Management', 'Consistent social presence through strategy, posting, and audience engagement.', 'Social', '/images/sevices/social media management.png', '["Monthly social media planning", "Content calendar and publishing", "Community management"]'::jsonb, '[{"value": "180+", "label": "Accounts Managed"}, {"value": "2M+", "label": "Audience Reach"}, {"value": "4.8×", "label": "Engagement Lift"}]'::jsonb, 4),
('brand-shoots', 'Brand Shoots', 'Professional photo and video shoots that elevate your brand identity.', 'Branding', '/images/sevices/brand shoots.png', '["Concept and moodboard planning", "On-location or studio shoots", "Brand-ready media selection"]'::jsonb, '[{"value": "120+", "label": "Brand Shoots"}, {"value": "2.5K+", "label": "Final Visuals"}, {"value": "96%", "label": "Client Satisfaction"}]'::jsonb, 5),
('performance-marketing', 'Performance Marketing', 'Data-driven paid and retention campaigns focused on conversions and measurable growth.', 'Paid Growth', '/images/sevices/perfomance marketing.png', '["Meta Ads", "Google Ads", "WhatsApp Campaigns", "Email Marketing"]'::jsonb, '[{"value": "250+", "label": "Campaigns"}, {"value": "500M+", "label": "Reach"}, {"value": "3.2×", "label": "Avg. ROAS"}]'::jsonb, 6)
ON CONFLICT (id) DO NOTHING;

INSERT INTO portfolio_items (id, title, client, category, type, industry, result, description, image, video_src, aspect, span, featured, order_index) VALUES
('turnup-aftermovie', 'Crown Plaza Turn Up Aftermovie', 'Crowne Plaza Hotels', 'Hospitality & Events', 'video', 'Luxury Hospitality', '1.8M+ video impressions across platforms', 'High-energy event aftermovie and visual storytelling for Crowne Plaza''s flagship summer festival.', '/images/portfolio-social.png', '/videos/turnup-aftermovie.mp4', '16:9', 'lg', true, 1),
('crown-plaza-turnup', 'Crown Plaza Festival Promo', 'Crowne Plaza Hotels', 'Hospitality & Events', 'video', 'Luxury Hospitality', '850K+ organic views & ticket sell-out', 'Cinematic commercial reel capturing luxury ambiance, live music, and party energy.', '/images/portfolio-email.png', '/videos/turn-up-crown-plaza.mp4', '16:9', 'md', true, 2),
('emarath-interior', 'Emarath Architectural Showcase', 'Emarath Interiors', 'Real Estate & Interiors', 'video', 'Interior Architecture', '3.4× increase in qualified luxury inquiries', 'Cinematic interior walkthrough showcasing modern Scandinavian aesthetics and premium craftsmanship.', '/images/portfolio-product.png', '/videos/emarath-interior-finalll-draft-preview.mp4', '16:9', 'md', true, 3),
('got-emarath', 'GOT Emarath Interior Film', 'Emarath Interiors', 'Real Estate & Interiors', 'video', 'Real Estate & Architecture', 'National design recognition & feature', 'Full-length interior design documentary capturing space planning, textures, and ambient lighting.', '/images/portfolio-web.png', '/videos/got-emarath-1.mp4', '16:9', 'lg', false, 4),
('fit-co-reel-1', 'Fit & Co Brand Launch Reel', 'Fit & Co Gyms', 'Fitness & Lifestyle', 'video', 'Fitness & Health', '4.8× engagement lift on Instagram Reels', 'Fast-paced mobile reel engineered for maximum scroll-stopping engagement and membership conversions.', '/images/portfolio-seo.png', '/videos/fitandco-reel-1.mp4', '9:16', 'sm', true, 5),
('fit-co-reel-2', 'Fit & Co High-Intensity Reel', 'Fit & Co Gyms', 'Fitness & Lifestyle', 'video', 'Fitness & Health', '320K+ views on Instagram & Shorts', 'Dynamic workout reel highlighting trainer sessions, high-energy beats, and community vibes.', '/images/portfolio-ppc.png', '/videos/reel-2-fitgo.mp4', '9:16', 'sm', false, 6),
('godha-reel', 'Godha Fitness Action Film', 'Godha Fitness', 'Fitness & Lifestyle', 'video', 'Sports & Athletics', '5.2× reach lift among fitness enthusiasts', 'Raw cinematic edit focusing on athletic strength, endurance, and brand identity.', '/images/portfolio-social.png', '/videos/godha-reel-final.mp4', '9:16', 'sm', false, 7),
('chefs-kiss', 'Chef''s Kiss Culinary Story', 'Chef''s Kiss Dining', 'Food & Brand Shoots', 'video', 'Culinary & Dining', '250K+ organic views in 14 days', 'Sensory food cinematography capturing artisanal prep, plating perfection, and kitchen atmosphere.', '/images/portfolio-ppc.png', '/videos/chefs-kiss-final-out.mp4', '9:16', 'sm', true, 8),
('boss-reel', 'Boss Brand Commercial', 'Boss Wear & Lifestyle', 'Food & Brand Shoots', 'video', 'Apparel & Lifestyle', '420K+ campaign reach across South India', 'Commercial film blending street culture aesthetics with sleek high-fashion product videography.', '/images/portfolio-web.png', '/videos/boss-reel-final.mp4', '16:9', 'lg', true, 9),
('aicademy-promo', 'Aicademy Future Learning', 'Aicademy Global', 'EdTech & Tech', 'video', 'EdTech', '2.1× signup conversion rate lift', 'Modern promotional video highlighting AI-powered education and interactive learning paths.', '/images/portfolio-email.png', '/videos/aicademy-new-reel.mp4', '9:16', 'sm', false, 10),
('getwork-app', 'GetWork Platform Launch', 'GetWork App', 'EdTech & Tech', 'video', 'SaaS & Tech', '180K+ app install impressions', 'Sleek motion graphics and video ad showcasing seamless user workflow and career matching.', '/images/portfolio-product.png', '/videos/getwork-vid-fdraft-2.mp4', '16:9', 'md', false, 11),
('keyboard-reel', 'Tech Gadget Product Reel', 'Tech Brand Lab', 'EdTech & Tech', 'video', 'Consumer Electronics', '3.9× CTR lift on product ads', 'Close-up macro product video emphasizing tactile switches, RGB lighting, and build precision.', '/images/portfolio-seo.png', '/videos/keyboard-reel-final-draftt.mp4', '9:16', 'sm', false, 12),
('happy-campaign', 'Happy Brand Event Film', 'Happy Media', 'Hospitality & Events', 'video', 'Entertainment', '500K+ cross-platform views', 'Vibrant event campaign film showcasing celebratory moments, crowd energy, and festival visuals.', '/images/portfolio-social.png', '/videos/happy-2.mp4', '16:9', 'md', false, 13),
('picha-narrative', 'Picha Brand Narrative Film', 'Picha Studios', 'Food & Brand Shoots', 'video', 'Brand Film', 'Featured storytelling award winner', 'Cinematic story-driven brand film blending deep character narrative with rich visual tone.', '/images/portfolio-product.png', '/videos/picha-final-out.mp4', '16:9', 'lg', true, 14),
('revathy-reel', 'Revathy Creator & Lifestyle Reel', 'Revathy Media', 'Fitness & Lifestyle', 'video', 'Personal Brand & Fashion', '92K+ organic impressions', 'Minimalist fashion aesthetic reel focused on personal branding and social engagement.', '/images/portfolio-seo.png', '/videos/revathy-reel-1draft.mp4', '9:16', 'sm', false, 15)
ON CONFLICT (id) DO NOTHING;
